/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-27 09:47:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/reboard/inc/lib.jsp", Long.valueOf(1624595104522L));
    _jspx_dependants.put("/reboard/inc/footer.jsp", Long.valueOf(1624595091205L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

//답변 등록에 필요한 파라미터를 넘겨받자..
	String team = request.getParameter("team");
	String step = request.getParameter("step"); 
	String depth = request.getParameter("depth");

      out.write('\r');
      out.write('\n');
      out.print(team );
      out.write('\r');
      out.write('\n');
      out.print(step );
      out.write('\r');
      out.write('\n');
      out.print(depth );
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<style>\r\n");
      out.write("#box {\r\n");
      out.write("	border: 1px solid #CCCCCC\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#writer, #title, #content {\r\n");
      out.write("	font-size: 9pt;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #7F7F7F;\r\n");
      out.write("	돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	font-size: 9pt;\r\n");
      out.write("	border-left: 1px solid #C3C3C3;\r\n");
      out.write("	border-top: 1px solid #C3C3C3;\r\n");
      out.write("	border-right: 1px solid #C3C3C3;\r\n");
      out.write("	border-bottom: 1px solid #C3C3C3;\r\n");
      out.write("	color: #7F7F7F;\r\n");
      out.write("	돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title input {\r\n");
      out.write("	width: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content textarea {\r\n");
      out.write("	width: 503px;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	height: 153;\r\n");
      out.write("	background: url(\"/reboard/images/write_bg.gif\");\r\n");
      out.write("	border: #C3C3C3 1px solid\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright {\r\n");
      out.write("	font-size: 9pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	border: 0px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function reply() {\r\n");
      out.write("		$(\"form\").attr({\r\n");
      out.write("			\"action\":\"/reboard/reply\",\r\n");
      out.write("			\"method\":\"post\"\r\n");
      out.write("		});\r\n");
      out.write("		$(\"form\").submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("답변 등록 폼\r\n");
      out.write("	<form>\r\n");
      out.write("		<input type=\"hidden\" name = \"team\" value=\"");
      out.print(team);
      out.write("\"> \r\n");
      out.write("	<input type=\"hidden\" name = \"step\" value=\"");
      out.print(step);
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" name = \"depth\" value=\"");
      out.print(depth);
      out.write("\">\r\n");
      out.write("		<table id=\"box\" align=\"center\" width=\"603\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("			cellspacing=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><img src=\"/reboard/images/ceil.gif\" width=\"603\" height=\"25\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"2\" bgcolor=\"#6395FA\"><img\r\n");
      out.write("					src=\"/reboard/images/line_01.gif\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"1\" bgcolor=\"#CCCCCC\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td id=\"list\"><table width=\"100%\" border=\"0\" cellspacing=\"0\"\r\n");
      out.write("						cellpadding=\"0\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td width=\"100\">&nbsp;</td>\r\n");
      out.write("							<td>&nbsp;</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr id=\"title\">\r\n");
      out.write("							<td height=\"25\" align=\"center\">제목</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"title\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr id=\"writer\">\r\n");
      out.write("							<td height=\"25\" align=\"center\">작성자</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"writer\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr id=\"content\">\r\n");
      out.write("							<td align=\"center\">내용</td>\r\n");
      out.write("							<td><textarea name=\"content\" style=\"\"></textarea></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>&nbsp;</td>\r\n");
      out.write("							<td>&nbsp;</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"30\" align=\"right\" style=\"padding-right: 2px;\"><img\r\n");
      out.write("					src=\"/reboard/images/write_btin.gif\" width=\"61\" height=\"20\"\r\n");
      out.write("					onClick=\"reply()\"> <a href=\"list.jsp\"><img\r\n");
      out.write("						src=\"/reboard/images/list_btn.gif\" width=\"61\" height=\"20\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"1\" bgcolor=\"#CCCCCC\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td height=\"20\" colspan=\"5\" align=\"center\" id=\"copyright\">Copyright zino All\r\n");
      out.write("		Rights Reserved</td>\r\n");
      out.write("</tr>");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
